# Generated by Django 5.1.3 on 2025-12-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='expertise/', verbose_name='Image')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('full_content', models.TextField(help_text='HTML content allowed', verbose_name='Full Content')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Expertise Card',
                'verbose_name_plural': 'Expertise Cards',
                'ordering': ['order'],
            },
        ),
    ]
