# Generated by Django 5.1.3 on 2025-12-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
    ]
