# Generated by Django 5.1.3 on 2025-12-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertisecard',
            name='full_content_el',
            field=models.TextField(help_text='HTML content allowed', null=True, verbose_name='Full Content'),
        ),
        migrations.AddField(
            model_name='expertisecard',
            name='full_content_en',
            field=models.TextField(help_text='HTML content allowed', null=True, verbose_name='Full Content'),
        ),
        migrations.AddField(
            model_name='expertisecard',
            name='full_content_ru',
            field=models.TextField(help_text='HTML content allowed', null=True, verbose_name='Full Content'),
        ),
        migrations.AddField(
            model_name='expertisecard',
            name='short_description_el',
            field=models.TextField(null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='expertisecard',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='expertisecard',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='expertisecard',
            name='title_el',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='expertisecard',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='expertisecard',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
