# Generated by Django 5.1.3 on 2025-12-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_protectionstandard'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_el', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(help_text='HTML content allowed', verbose_name='Content')),
                ('content_en', models.TextField(help_text='HTML content allowed', null=True, verbose_name='Content')),
                ('content_el', models.TextField(help_text='HTML content allowed', null=True, verbose_name='Content')),
                ('content_ru', models.TextField(help_text='HTML content allowed', null=True, verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
            },
        ),
    ]
